#!/usr/bin/env python3
"""Generate completed-study tables and figures from frozen result files."""
import argparse
import csv
import hashlib
import json
import math
import statistics
from collections import Counter
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


PARTITIONS = ("fitting", "development", "evaluation")
CONDITIONS = ("full", "random_subsample23", "clean_consensus")
MODELS = {
    "ResNet50": ("consensus_23_resnet50_v1", "resnet50"),
    "ConvNeXt-Tiny": ("consensus_23_convnext_tiny_v2", "convnext_tiny"),
    "Swin-Tiny": ("consensus_23_swin_tiny_v1", "swin_tiny"),
}
EXTERNAL_STUDIES = {
    "Malimg": {
        "subdir": "malimg_resnet50_seed42_v1",
        "model": "resnet50",
        "conditions": ("full", "random_subsample20", "clean_consensus"),
        "labels": ("Full-20", "Random-Subsample-20", "Clean-Consensus-20"),
        "architecture": "ResNet50",
    },
    "Virus-MNIST": {
        "subdir": "virusmnist_spatial_cnn_5seeds_v1",
        "model": "spatial_cnn",
        "conditions": ("full", "random_subsample9", "clean_consensus"),
        "labels": ("Full-9", "Random-Subsample-9", "Clean-Consensus-9"),
        "architecture": "Spatial CNN",
    },
}
SEEDS = (42, 101, 7, 2024, 99)
T_CRIT_DF4 = 2.7764451051977987


def read_csv(path):
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def table(out, name, lines):
    path = out / "tables" / name
    path.write_text(
        "% Generated by tools/generate_completed_assets.py; do not edit.\n"
        + "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def mean_sd(values):
    return statistics.mean(values), statistics.stdev(values)


def fmt_mean_sd(values):
    mean, sd = mean_sd(values)
    return f"{mean:.2f} $\\pm$ {sd:.2f}"


def metric_index(root, subdir, model):
    values = {}
    for path in (root / subdir / model).glob("*/seed_*/metrics.json"):
        row = json.loads(path.read_text(encoding="utf-8"))
        values[(row["condition"], int(row["seed"]))] = row
    expected = {(condition, seed) for condition in CONDITIONS for seed in SEEDS}
    if set(values) != expected:
        raise ValueError(
            f"Incomplete {model} results: missing {sorted(expected - set(values))}"
        )
    return values


def external_metric_index(root, study):
    values = {}
    for path in (root / study["subdir"] / study["model"]).glob(
        "*/seed_*/metrics.json"
    ):
        row = json.loads(path.read_text(encoding="utf-8"))
        values[(row["condition"], int(row["seed"]))] = row
    expected = {
        (condition, seed)
        for condition in study["conditions"] for seed in SEEDS
    }
    if set(values) != expected:
        raise ValueError(
            f"Incomplete {study['model']} external results: "
            f"missing {sorted(expected - set(values))}"
        )
    return values


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--annotation-1", type=Path, required=True)
    parser.add_argument("--annotation-2", type=Path, required=True)
    args = parser.parse_args()
    project = args.project.resolve()
    results = project / "results"
    out = Path(__file__).resolve().parents[1]
    sources = {}

    def record(path):
        path = Path(path).resolve()
        sources[str(path)] = digest(path)
        return path

    # Dataset conditions and consensus cleaning.
    summary_path = record(
        results / "consensus_23_resnet50_v1" / "four_condition_dataset_summary.csv"
    )
    condition_rows = {
        row["condition"]: row for row in read_csv(summary_path)
    }
    labels = {
        "full": "Full-23",
        "random_subsample23": "Random-Subsample-23",
        "clean_consensus": "Clean-Consensus-23",
    }
    lines = []
    for condition in CONDITIONS:
        row = condition_rows[condition]
        matched = int(row["evaluation_images_matching_fitting_group"])
        evaluation = int(row["evaluation"])
        lines.append(
            f"{labels[condition]} & {int(row['images']):,} & "
            f"{int(row['fitting']):,} & {int(row['development']):,} & "
            f"{evaluation:,} & {int(row['distinct_consensus_groups']):,} & "
            f"{matched:,} ({100 * matched / evaluation:.2f}\\%) \\\\"
        )
    table(out, "condition_rows.tex", lines)

    clean_class_path = record(
        results / "dedup_before_split_consensus_23class_v1" / "per_class.csv"
    )
    clean_classes = read_csv(clean_class_path)
    lines = []
    for row in clean_classes:
        retained = int(row["retained_groups"])
        status = "Excluded" if retained < 50 else "Retained"
        lines.append(
            f"{row['class_label']} & {int(row['original_images']):,} & "
            f"{retained:,} & {int(row['removed_excess_copies']):,} & "
            f"{float(row['removed_percent']):.2f}\\% & {status} \\\\"
        )
    table(out, "cleaning_class_rows.tex", lines)

    # Make class concentration visible in the main text. The table remains in
    # the appendix for exact counts.
    ordered_clean = sorted(
        clean_classes, key=lambda row: float(row["removed_percent"])
    )
    fig, axis = plt.subplots(figsize=(7.2, 6.0), layout="constrained")
    percentages = [float(row["removed_percent"]) for row in ordered_clean]
    colors = [
        "#a33a3a" if int(row["retained_groups"]) < 50 else "#2f6f91"
        for row in ordered_clean
    ]
    axis.barh(
        np.arange(len(ordered_clean)), percentages, color=colors,
        edgecolor="none"
    )
    axis.set_yticks(
        np.arange(len(ordered_clean)),
        [row["class_label"] for row in ordered_clean], fontsize=7.5,
    )
    axis.set_xlabel(r"Images removed by complete-hash-tuple grouping (\%)")
    axis.set_xlim(0, 100)
    axis.grid(axis="x", alpha=0.25)
    axis.set_axisbelow(True)
    axis.spines[["top", "right"]].set_visible(False)
    fig.savefig(out / "figures" / "class_consensus_removal.pdf")
    plt.close(fig)

    # Model metrics and paired contrasts.
    model_data = {}
    source_paths = []
    for display, (subdir, model) in MODELS.items():
        data = metric_index(results, subdir, model)
        model_data[display] = data
        source_paths.extend(
            results / subdir / model / condition / f"seed_{seed}" / "metrics.json"
            for condition in CONDITIONS for seed in SEEDS
        )
    for path in source_paths:
        record(path)

    lines = []
    for display, data in model_data.items():
        for condition in CONDITIONS:
            rows = [data[(condition, seed)] for seed in SEEDS]
            values = {
                metric: [100 * row[metric] for row in rows]
                for metric in ("accuracy", "macro_f1", "macro_recall")
            }
            lines.append(
                f"{display} & {labels[condition]} & "
                f"{fmt_mean_sd(values['accuracy'])} & "
                f"{fmt_mean_sd(values['macro_f1'])} & "
                f"{fmt_mean_sd(values['macro_recall'])} \\\\"
            )
    table(out, "model_performance_rows.tex", lines)

    contrast_summary = {}
    lines = []
    for display, data in model_data.items():
        for key, first, second, label in (
            ("full_clean", "full", "clean_consensus", "Full $-$ Clean"),
            ("random_clean", "random_subsample23", "clean_consensus",
             "Random $-$ Clean"),
        ):
            diffs = {}
            for metric in ("accuracy", "macro_f1", "macro_recall"):
                diffs[metric] = [
                    100 * (
                        data[(first, seed)][metric]
                        - data[(second, seed)][metric]
                    ) for seed in SEEDS
                ]
            acc_mean, acc_sd = mean_sd(diffs["accuracy"])
            margin = T_CRIT_DF4 * acc_sd / math.sqrt(len(SEEDS))
            contrast_summary[(display, key)] = {
                "accuracy_mean": acc_mean,
                "accuracy_sd": acc_sd,
                "accuracy_ci": [acc_mean - margin, acc_mean + margin],
                "macro_f1_mean": statistics.mean(diffs["macro_f1"]),
                "macro_recall_mean": statistics.mean(diffs["macro_recall"]),
                "accuracy_values": diffs["accuracy"],
            }
            lines.append(
                f"{display} & {label} & {acc_mean:+.2f} $\\pm$ {acc_sd:.2f} & "
                f"[{acc_mean-margin:+.2f}, {acc_mean+margin:+.2f}] & "
                f"{statistics.mean(diffs['macro_f1']):+.2f} & "
                f"{statistics.mean(diffs['macro_recall']):+.2f} \\\\"
            )
    table(out, "model_contrast_rows.tex", lines)

    # Cross-dataset audit census. MaleVis values come from the primary audit;
    # the two external rows come from the frozen common audit.
    malevis_hash_path = record(results / "hash_audit_v1" / "summary.csv")
    malevis_hash = {
        row["method"]: row for row in read_csv(malevis_hash_path)
    }
    malevis_protocol_path = record(
        results / "dedup_before_split_consensus_23class_v1" / "protocol.json"
    )
    malevis_protocol = json.loads(malevis_protocol_path.read_text())
    external_audit_path = record(
        results / "external_consensus_audit_v1" / "comparison_summary.csv"
    )
    external_audit = {
        row["dataset"]: row for row in read_csv(external_audit_path)
    }
    rgb_row = malevis_hash["rgb_sha256"]
    malevis_images = int(rgb_row["train_samples"]) + int(rgb_row["eval_samples"])
    malevis_exact_excess = malevis_images - int(rgb_row["unique_groups_global"])
    audit_lines = [
        f"MaleVis & {malevis_images:,} & 26 & "
        f"{malevis_exact_excess:,} ({100 * malevis_exact_excess / malevis_images:.2f}\\%) & "
        f"{int(malevis_protocol['removed_excess_copies']):,} "
        f"({100 * int(malevis_protocol['removed_excess_copies']) / malevis_images:.2f}\\%) & 23 \\\\"
    ]
    for dataset in ("Malimg", "Virus-MNIST"):
        row = external_audit[dataset]
        audit_lines.append(
            f"{dataset} & {int(row['images']):,} & {int(row['classes'])} & "
            f"{int(row['exact_rgb_excess']):,} "
            f"({100 * float(row['exact_rgb_redundancy_fraction']):.2f}\\%) & "
            f"{int(row['consensus_excess']):,} "
            f"({100 * float(row['consensus_redundancy_fraction']):.2f}\\%) & "
            f"{int(row['eligible_classes'])} \\\\"
        )
    table(out, "cross_dataset_audit_rows.tex", audit_lines)

    # External five-seed performance and paired size-matched contrasts.
    external_data = {}
    lines = []
    external_contrasts = {}
    external_contrast_lines = []
    for dataset, study in EXTERNAL_STUDIES.items():
        data = external_metric_index(results, study)
        external_data[dataset] = data
        for path in (
            results / study["subdir"] / study["model"] / condition
            / f"seed_{seed}" / "metrics.json"
            for condition in study["conditions"] for seed in SEEDS
        ):
            record(path)
        for condition, label in zip(study["conditions"], study["labels"]):
            rows = [data[(condition, seed)] for seed in SEEDS]
            values = {
                metric: [100 * row[metric] for row in rows]
                for metric in ("accuracy", "macro_f1", "macro_recall")
            }
            lines.append(
                f"{dataset} & {study['architecture']} & {label} & "
                f"{fmt_mean_sd(values['accuracy'])} & "
                f"{fmt_mean_sd(values['macro_f1'])} & "
                f"{fmt_mean_sd(values['macro_recall'])} \\\\"
            )
        random_condition = study["conditions"][1]
        diffs = {
            metric: [
                100 * (
                    data[(random_condition, seed)][metric]
                    - data[("clean_consensus", seed)][metric]
                ) for seed in SEEDS
            ] for metric in ("accuracy", "macro_f1", "macro_recall")
        }
        acc_mean, acc_sd = mean_sd(diffs["accuracy"])
        margin = T_CRIT_DF4 * acc_sd / math.sqrt(len(SEEDS))
        external_contrasts[dataset] = {
            "mean": acc_mean,
            "sd": acc_sd,
            "low": acc_mean - margin,
            "high": acc_mean + margin,
        }
        external_contrast_lines.append(
            f"{dataset} & {study['architecture']} & "
            f"{acc_mean:+.2f} $\\pm$ {acc_sd:.2f} & "
            f"[{acc_mean-margin:+.2f}, {acc_mean+margin:+.2f}] & "
            f"{statistics.mean(diffs['macro_f1']):+.2f} & "
            f"{statistics.mean(diffs['macro_recall']):+.2f} \\\\"
        )
    table(out, "external_performance_rows.tex", lines)
    table(out, "external_contrast_rows.tex", external_contrast_lines)

    # Put the primary size-matched contrast from all completed experiments on
    # one scale. Intervals summarize only the five paired optimization seeds.
    plot_rows = []
    for model in MODELS:
        item = contrast_summary[(model, "random_clean")]
        plot_rows.append((f"MaleVis / {model}", item["accuracy_mean"],
                          item["accuracy_ci"][0], item["accuracy_ci"][1],
                          "#275d7a"))
    for dataset in ("Malimg", "Virus-MNIST"):
        item = external_contrasts[dataset]
        color = "#d1872c" if dataset == "Malimg" else "#26856b"
        plot_rows.append((
            f"{dataset} / {EXTERNAL_STUDIES[dataset]['architecture']}",
            item["mean"], item["low"], item["high"], color,
        ))
    fig, axis = plt.subplots(figsize=(7.2, 3.5), layout="constrained")
    y = np.arange(len(plot_rows))[::-1]
    means = np.array([row[1] for row in plot_rows])
    lows = np.array([row[2] for row in plot_rows])
    highs = np.array([row[3] for row in plot_rows])
    axis.errorbar(
        means, y, xerr=np.vstack((means - lows, highs - means)),
        fmt="none", ecolor="#555555", elinewidth=1.2, capsize=3, zorder=2,
    )
    axis.scatter(
        means, y, c=[row[4] for row in plot_rows], s=38, zorder=3,
        edgecolor="white", linewidth=0.5,
    )
    axis.axvline(0, color="#333333", linewidth=0.8, linestyle="--")
    axis.set_yticks(y, [row[0] for row in plot_rows], fontsize=8)
    axis.set_xlabel("Random-Subsample minus Clean accuracy (percentage points)")
    axis.grid(axis="x", alpha=0.25)
    axis.set_axisbelow(True)
    axis.spines[["top", "right"]].set_visible(False)
    fig.savefig(out / "figures" / "cross_dataset_contrasts.pdf")
    plt.close(fig)

    # Per-class mean recall contrasts for the size-matched comparison.
    per_class_values = {}
    classes = None
    for display, (subdir, model) in MODELS.items():
        by_condition = {}
        for condition in ("random_subsample23", "clean_consensus"):
            per_seed = []
            for seed in SEEDS:
                path = record(
                    results / subdir / model / condition / f"seed_{seed}"
                    / "per_class.csv"
                )
                per_seed.append({row["class_label"]: row for row in read_csv(path)})
            current_classes = sorted(per_seed[0])
            if classes is None:
                classes = current_classes
            elif classes != current_classes:
                raise ValueError("Per-class model outputs use different classes.")
            by_condition[condition] = {
                label: statistics.mean(
                    100 * float(seed_rows[label]["recall"])
                    for seed_rows in per_seed
                ) for label in current_classes
            }
        per_class_values[display] = {
            label: (
                by_condition["random_subsample23"][label]
                - by_condition["clean_consensus"][label]
            ) for label in current_classes
        }
    lines = [
        f"{label} & {per_class_values['ResNet50'][label]:+.2f} & "
        f"{per_class_values['ConvNeXt-Tiny'][label]:+.2f} & "
        f"{per_class_values['Swin-Tiny'][label]:+.2f} \\\\"
        for label in classes
    ]
    table(out, "per_class_recall_contrast_rows.tex", lines)

    # Completed human annotations.
    allowed_judgments = {
        "visually_indistinguishable", "near_duplicate", "similar_texture",
        "different", "uncertain",
    }
    annotation_maps = []
    for path in (record(args.annotation_1), record(args.annotation_2)):
        rows = read_csv(path)
        if len(rows) != 550:
            raise ValueError(f"Expected 550 completed annotations in {path}.")
        current = {}
        for row in rows:
            pair_id = row["pair_id"].strip()
            judgment = row["judgement"].strip().lower()
            if not pair_id or not judgment:
                raise ValueError(f"Blank annotation field in {path}.")
            if pair_id in current:
                raise ValueError(f"Repeated pair ID {pair_id} in {path}.")
            if judgment not in allowed_judgments:
                raise ValueError(f"Unknown judgment {judgment!r} in {path}.")
            current[pair_id] = judgment
        annotation_maps.append(current)
    pair_path = record(results / "pair_review_v1" / "pair_metrics.csv")
    pairs = read_csv(pair_path)
    if {row["pair_id"] for row in pairs} != set(annotation_maps[0]):
        raise ValueError("Annotation IDs do not match the frozen pair sample.")
    common = sorted(annotation_maps[0])
    observed_agreement = statistics.mean(
        annotation_maps[0][pair_id] == annotation_maps[1][pair_id]
        for pair_id in common
    )
    labels_seen = sorted(
        set(annotation_maps[0].values()) | set(annotation_maps[1].values())
    )
    counts_1 = Counter(annotation_maps[0].values())
    counts_2 = Counter(annotation_maps[1].values())
    expected_agreement = sum(
        counts_1[label] * counts_2[label] for label in labels_seen
    ) / len(common) ** 2
    kappa = (
        (observed_agreement - expected_agreement) / (1 - expected_agreement)
        if expected_agreement < 1 else 1.0
    )
    groups = (
        ("All hash candidates", lambda row: row["sample_kind"] == "candidate"),
        ("aHash only", lambda row: row["hash_mask"] == "1"),
        ("dHash only", lambda row: row["hash_mask"] == "2"),
        ("pHash only", lambda row: row["hash_mask"] == "4"),
        ("Exactly two hashes", lambda row: row["hash_mask"] in {"3", "5", "6"}),
        ("All three hashes", lambda row: row["hash_mask"] == "7"),
        ("No-hash controls", lambda row: row["sample_kind"] == "nonmatching_control"),
    )
    annotation_summary = {}
    lines = []
    for label, predicate in groups:
        selected = [row for row in pairs if predicate(row)]
        counts = [
            Counter(judgments[row["pair_id"]] for row in selected)
            for judgments in annotation_maps
        ]
        annotation_summary[label] = {
            "n": len(selected),
            "annotator_1": dict(counts[0]),
            "annotator_2": dict(counts[1]),
        }
        lines.append(
            f"{label} & {len(selected)} & "
            f"{counts[0]['visually_indistinguishable']}/{counts[1]['visually_indistinguishable']} & "
            f"{counts[0]['near_duplicate']}/{counts[1]['near_duplicate']} & "
            f"{counts[0]['similar_texture']}/{counts[1]['similar_texture']} & "
            f"{counts[0]['different']}/{counts[1]['different']} \\\\"
        )
    table(out, "annotation_rows.tex", lines)

    # Accuracy plot with all five seeds visible.
    fig, axes = plt.subplots(1, 3, figsize=(9.2, 3.3), sharey=True,
                             layout="constrained")
    colors = {"full": "#275d7a", "random_subsample23": "#d1872c",
              "clean_consensus": "#26856b"}
    x = np.arange(len(CONDITIONS))
    for axis, (display, data) in zip(axes, model_data.items()):
        means = []
        for index, condition in enumerate(CONDITIONS):
            values = np.array([
                100 * data[(condition, seed)]["accuracy"] for seed in SEEDS
            ])
            means.append(values.mean())
            axis.scatter(
                np.full(len(values), index) + np.linspace(-0.07, 0.07, len(values)),
                values, s=20, color=colors[condition], alpha=0.75, zorder=3,
            )
        axis.plot(x, means, color="#222222", marker="D", linewidth=1.2,
                  markersize=4, zorder=4)
        axis.set_title(display)
        axis.set_xticks(x, ["Full", "Random", "Clean"], rotation=20)
        axis.grid(axis="y", alpha=0.25)
        axis.spines[["top", "right"]].set_visible(False)
    axes[0].set_ylabel(r"Evaluation accuracy (\%)")
    fig.savefig(out / "figures" / "model_accuracy.pdf")
    plt.close(fig)

    macros = {
        "AnnotationAgreementPct": f"{100 * observed_agreement:.2f}",
        "AnnotationKappa": f"{kappa:.2f}",
        "ConsensusRemoved": "5,245",
        "ConsensusRetained": "8,981",
        "ExcludedClassCount": "3",
        "ControlledEffectMin": f"{min(contrast_summary[(m, 'random_clean')]['accuracy_mean'] for m in MODELS):.2f}",
        "ControlledEffectMax": f"{max(contrast_summary[(m, 'random_clean')]['accuracy_mean'] for m in MODELS):.2f}",
    }
    with (out / "numbers_completed.tex").open("w", encoding="utf-8") as handle:
        handle.write("% Generated from completed annotation and model outputs.\n")
        for name, value in macros.items():
            handle.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")

    analysis = {
        "annotation": {
            "observed_agreement": observed_agreement,
            "cohen_kappa": kappa,
            "counts_per_annotator": [dict(counts_1), dict(counts_2)],
            "sample_groups": annotation_summary,
        },
        "contrasts": {
            f"{model}:{contrast}": values
            for (model, contrast), values in contrast_summary.items()
        },
        "source_sha256": sources,
        "generator_sha256": digest(Path(__file__)),
    }
    (out / "completed_study_provenance.json").write_text(
        json.dumps(analysis, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        f"Generated completed-study assets from {len(sources)} files; "
        f"annotation agreement={observed_agreement:.3f}, kappa={kappa:.3f}."
    )


if __name__ == "__main__":
    main()
