#!/usr/bin/env python3
"""Generate manuscript assets from frozen audit outputs; never alter the dataset."""
import argparse
import csv
import hashlib
import json
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np


def read_csv(path):
    with path.open(newline='') as stream:
        return list(csv.DictReader(stream))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project', type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    out = Path(__file__).resolve().parents[1]
    results = args.project / 'results'
    sources = {}

    def source(subdir, name):
        path = results / subdir / name
        sources[str(path.relative_to(args.project))] = hashlib.sha256(path.read_bytes()).hexdigest()
        return path

    metas = [json.loads(source(sub, 'run_metadata.json').read_text()) for sub in
             ['exact_audit_v1', 'hash_audit_v1', 'pair_review_v1']]
    snapshots = {meta['dataset_snapshot_sha256'] for meta in metas}
    if len(snapshots) != 1:
        raise ValueError('Audit snapshot identifiers differ')
    exact = json.loads(source('exact_audit_v1', 'summary.json').read_text())
    hashes = {r['method']: r for r in read_csv(source('hash_audit_v1', 'summary.csv'))}
    per_class = {(r['method'], r['class_label']): r for r in read_csv(source('hash_audit_v1', 'per_class.csv'))}
    exact_class = {(r['level'], r['class_label']): r for r in read_csv(source('exact_audit_v1', 'per_class.csv'))}
    pairs = read_csv(source('pair_review_v1', 'pair_metrics.csv'))
    assert len(pairs) == metas[2]['candidate_pairs_sampled'] + metas[2]['nonmatching_controls_sampled']
    assert len({r['pair_id'] for r in pairs}) == len(pairs)
    for method, row in hashes.items():
        assert abs(float(row['eval_overlap_fraction']) - int(row['eval_matched_samples']) / int(row['eval_samples'])) < 1e-12
    assert int(hashes['sha256']['eval_matched_samples']) == exact['file']['val_overlap_count']
    assert int(hashes['rgb_sha256']['eval_matched_samples']) == exact['rgb_pixels']['val_overlap_count']

    def table(name, lines):
        (out / 'tables' / name).write_text('% Generated by tools/generate_assets.py; do not edit.\n' + '\n'.join(lines) + '\n')

    lines = []
    for key, label in [('file', 'Image-file bytes'), ('rgb_pixels', 'Native RGB pixels'), ('model_input', r'224$\times$224 audit transform')]:
        r = exact[key]
        vals = [r['unique_groups_global'], r['train_excess_copies'], r['val_excess_copies'], r['val_overlap_count']]
        lines.append(label + ' & ' + ' & '.join(f'{v:,}' for v in vals) + f" & {100*r['val_overlap_fraction']:.2f}" + r'\% \\')
    table('exact_rows.tex', lines)
    labels = [('ahash', 'aHash'), ('dhash', 'dHash'), ('phash', 'pHash'),
              ('union_1_of_3', 'At least one'), ('majority_2_of_3', 'At least two'), ('intersection_3_of_3', 'All three')]
    lines = []
    for key, label in labels:
        r = hashes[key]
        lines.append(label + f" & {int(r['eval_matched_samples']):,} & {100*float(r['eval_overlap_fraction']):.2f}" + r'\%' +
                     f" & {int(r['matching_train_eval_pairs']):,} & {int(r['eval_other_label_matched_samples']):,}" + r' \\')
    table('hash_rows.tex', lines)
    lines = []
    for cls in ['VBA', 'Snarasite', 'Vilsel']:
        p, e = per_class['phash', cls], per_class['rgb_sha256', cls]
        lines.append(f"{cls} & {e['train_samples']} & {e['train_unique_groups']} & {p['train_unique_groups']} & {p['eval_matched_samples']}/{p['eval_samples']}" + r' \\')
    table('family_rows.tex', lines)
    lines = []
    for cls in ['Amonetize', 'Fasong', 'Other', 'VBA']:
        e, m = exact_class['rgb_pixels', cls], exact_class['model_input', cls]
        lines.append(f"{cls} & {e['val_samples']} & {e['val_overlap_any_label']} & {m['val_overlap_any_label']}" + r' \\')
    table('exact_class_rows.tex', lines)

    groups = [
        ('All candidates', lambda r: r['sample_kind'] == 'candidate'),
        ('pHash matches', lambda r: r['phash_match'] == '1'),
        ('All-three matches', lambda r: r['hash_mask'] == '7'),
        ('All-three, nonidentical', lambda r: r['hash_mask'] == '7' and r['native_exact_rgb'] == '0'),
        ('Nonmatching controls', lambda r: r['sample_kind'] == 'nonmatching_control')]
    summaries = {}
    lines = []
    for label, predicate in groups:
        selected = [r for r in pairs if predicate(r)]
        mae = np.array([float(r['native_mean_abs_channel_diff_255']) for r in selected])
        ssim = np.array([float(r['native_ssim_rgb']) for r in selected])
        summaries[label] = {'n': len(selected), 'exact': sum(int(r['native_exact_rgb']) for r in selected),
                            'mae_median': float(np.median(mae)), 'ssim_median': float(np.median(ssim)),
                            'ssim_min': float(ssim.min()), 'ssim_max': float(ssim.max())}
        s = summaries[label]
        lines.append(f"{label} & {s['n']} & {s['exact']} & {s['mae_median']:.4f} & {s['ssim_median']:.6f} & {s['ssim_min']:.6f}" + r' \\')
    table('pair_rows.tex', lines)

    macros = {
        'ExactCount': str(exact['file']['val_overlap_count']),
        'ExactPct': f"{100*exact['file']['val_overlap_fraction']:.2f}",
        'InputCount': str(exact['model_input']['val_overlap_count']),
        'InputPct': f"{100*exact['model_input']['val_overlap_fraction']:.2f}",
        'PhashCount': f"{int(hashes['phash']['eval_matched_samples']):,}",
        'PhashPct': f"{100*float(hashes['phash']['eval_overlap_fraction']):.2f}",
        'IntersectionCount': f"{int(hashes['intersection_3_of_3']['eval_matched_samples']):,}",
        'IntersectionPct': f"{100*float(hashes['intersection_3_of_3']['eval_overlap_fraction']):.2f}",
        'NonexactThreeN': str(summaries['All-three, nonidentical']['n']),
        'NonexactThreeSSIM': f"{summaries['All-three, nonidentical']['ssim_median']:.6f}",
        'NonexactThreeMAE': f"{summaries['All-three, nonidentical']['mae_median']:.4f}",
    }
    (out/'numbers.tex').write_text('% Generated from frozen audit outputs.\n' + '\n'.join(
        '\\newcommand{\\' + key + '}{' + value + '}' for key, value in macros.items()) + '\n')

    plt.rcParams.update({'font.size': 10, 'pdf.fonttype': 42, 'ps.fonttype': 42})
    fig, ax = plt.subplots(figsize=(7.2, 3.5), layout='constrained')
    methods = [('sha256', 'File / native RGB')] + labels
    values = [100*float(hashes[key]['eval_overlap_fraction']) for key, _ in methods]
    ax.barh([label for _, label in methods], values, color=['#186b68'] + ['#72869b']*6)
    ax.invert_yaxis(); ax.set_xlim(0, 88)
    ax.set_xlabel('Validation images with a training match (%)')
    for i, value in enumerate(values): ax.text(value+1, i, f'{value:.2f}%', va='center', fontsize=9)
    ax.spines[['top', 'right']].set_visible(False)
    fig.savefig(out/'figures/overlap.pdf'); plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(8, 3.2), layout='constrained')
    plotgroups = [('All-three', lambda r: r['hash_mask'] == '7', '#186b68'),
                  ('pHash, fewer than three', lambda r: r['phash_match'] == '1' and r['hash_mask'] != '7', '#cc7c27'),
                  ('No hash match (controls)', lambda r: r['sample_kind'] == 'nonmatching_control', '#7b5ba7')]
    for label, predicate, color in plotgroups:
        selected = [r for r in pairs if predicate(r)]
        for ax, key in zip(axes, ['native_mean_abs_channel_diff_255', 'native_ssim_rgb']):
            values = np.sort([float(r[key]) for r in selected])
            ax.step(values, np.arange(1,len(values)+1)/len(values), where='post', color=color, label=f'{label} (n={len(values)})')
    axes[0].set_xscale('symlog', linthresh=.001)
    axes[0].set_xlabel('Native MAE (0–255; symmetric log scale)')
    axes[1].set_xlabel('Native RGB SSIM')
    axes[0].set_ylabel('Fraction of sampled pairs')
    for ax in axes:
        ax.set_ylim(0,1.03); ax.spines[['top','right']].set_visible(False)
    axes[1].legend(loc='lower right', fontsize=7)
    fig.savefig(out/'figures/pair_distributions.pdf'); plt.close(fig)

    # Full per-class appendix keeps small selected-family tables in context.
    lines = []
    for cls in sorted({key[1] for key in per_class}):
        e, p, a = per_class['rgb_sha256', cls], per_class['phash', cls], per_class['intersection_3_of_3', cls]
        lines.append(f"{cls} & {e['eval_samples']} & {e['eval_matched_samples']} & {p['eval_matched_samples']} & {a['eval_matched_samples']}" + r' \\')
    table('all_class_rows.tex', lines)
    (out/'asset_provenance.json').write_text(json.dumps({'dataset_snapshot_sha256': next(iter(snapshots)),
        'source_sha256': sources, 'sample_summaries': summaries,
        'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}, indent=2)+'\n')
    print(f'Generated assets from {len(sources)} audit files; snapshot {next(iter(snapshots))}')


if __name__ == '__main__':
    main()
